name: "Action: Setup node"
description: 'Composite setup node action'

runs:
    using: "composite"
    steps:
        - uses: actions/setup-node@v3
          with:
              node-version-file: .nvmrc
              cache: 'yarn'

        - name: Install dependencies
          shell: sh
          run: yarn --frozen-lockfile
