name: "Action: Analyze"
description: 'Composite analyze action'

runs:
    using: "composite"
    steps:
        - name: Lint
          shell: sh
          run: yarn lint:ci
        - uses: github/codeql-action/upload-sarif@v2
          with:
              sarif_file: eslint-results.sarif
              wait-for-processing: true

        - name: CodeQL
          uses: github/codeql-action/init@v2
          with:
              languages: 'javascript'
        - uses: github/codeql-action/autobuild@v2
        - uses: github/codeql-action/analyze@v2
