name: "Action: Analyze"
description: 'Composite analyze action'

runs:
    using: "composite"
    steps:
        - uses: actions/checkout@v3

#        - uses: actions/setup-node@v3
#          with:
#              cache: 'yarn'
#        - shell: sh
#          run: yarn install --frozen-lockfile
        - uses: actions/cache@v3
          id: restore-build
          with:
              path: ./*
              key: ${{ runner.os }}-${{ github.sha }}

        - name: Lint
          shell: sh
          run: yarn lint:ci
        - uses: github/codeql-action/upload-sarif@v2
          with:
              sarif_file: eslint-results.sarif
              wait-for-processing: true

        - name: CodeQL
          uses: github/codeql-action/init@v2
          with:
              languages: 'javascript'
        - uses: github/codeql-action/autobuild@v2
        - uses: github/codeql-action/analyze@v2
