name: "Action: Release"
description: 'Composite release action'

inputs:
    node-version:
        description: Node.js version
        required: true
    npmToken:
        description: NPM Token
        required: true

runs:
    using: "composite"
    steps:
        - name: Version bump
          uses: phips28/gh-action-bump-version@master
          env:
              GITHUB_TOKEN: ${{ github.token }}
          with:
              major-wording: 'MAJOR,BREAKING CHANGE'
              minor-wording: 'MINOR,FEAT,CHORE'
              rc-wording: 'ALPHA,BETA'

        - name: Publish to NPM
          shell: sh
          run: |
              yarn copy
              echo "//registry.npmjs.org/:_authToken=${{ inputs.npmToken }}" >> ./.npmrc
              CI=1 npm publish lib/ --access public
