/* This file is autogenerated, do not edit - it will be overwritten anyway */

export type Icon =
    'authenticityGuaranteed' |
    'clickToCall' |
    'ebayPlus' |
    'escrow' |
    'freeWarranty' |
    'moneyBackGuaranteeChf' |
    'moneyBackGuaranteeEu' |
    'moneyBackGuaranteeUk' |
    'moneyBackGuaranteeUs' |
    'moneyBackGuaranteeZl' |
    'topRatedSeller' |
    'vault'
