name: "Action: Export to GSheets"
description: 'Composite export to google sheets action'

inputs:
    issueTitle:
        description: issue title
        required: false
    prTitle:
        description: PR title
        required: false
    url:
        description: URL
        required: false
    state:
        description: PR state
        required: false
    isMerged:
        description: is PR merged
        required: false
    isDraft:
        description: is PR a draft
        required: false
    review:
        description: PR review
        required: false
    assigned:
        description: assigned user name
        required: false
    googleSheetsKey:
        description: Google Sheets Key
        required: true

runs:
    using: "composite"
    steps:
        - shell: sh
          run: yarn add -D google-spreadsheet

        - if: inputs.issueTitle != ''
          shell: sh
          env:
              GKEY: ${{ inputs.googleSheetsKey }}
          run: node ./scripts/gsheet-issue "${{ inputs.issueTitle }}" "${{ inputs.url }}"

        - if: inputs.prTitle != ''
          shell: sh
          env:
              GKEY: ${{ inputs.googleSheetsKey }}
          run: node ./scripts/gsheet-pr "${{ inputs.prTitle }}" "${{ inputs.url }}" "${{ inputs.state }}" "${{ inputs.isMerged }}" "${{ inputs.isDraft }}" "${{ inputs.review }}" "${{ inputs.assigned }}"
