/* This file is autogenerated, do not edit - it will be overwritten anyway */

import { Icon } from '../types'

export const icons: Icon[] = [
    'authenticityGuaranteed',
    'clickToCall',
    'ebayPlus',
    'escrow',
    'freeWarranty',
    'moneyBackGuaranteeChf',
    'moneyBackGuaranteeEu',
    'moneyBackGuaranteeUk',
    'moneyBackGuaranteeUs',
    'moneyBackGuaranteeZl',
    'topRatedSeller',
    'vault'
]
