import { resolve } from 'path'
import { skinIcons, iconKeys, svgIcons } from '../update-icons-helpers.js'

const skinCollection = require('./icons.json')

describe('update-icons', () => {
    describe('skinIcons()', () => {
        it('should read icons from Skin', () => {
            expect(skinIcons(resolve(__dirname, './icons.svg'))).toEqual(skinCollection)
        })
        it('should throw if Skin not found', async () => {
            expect.hasAssertions()
            try {
                await skinIcons('not-exist.svg')
            } catch (e) {
                expect(e.code).toEqual('ENOENT')
            }
        })
    })
    describe('iconKeys()', () => {
        it('should extract keys from skin collection', () => {
            expect(iconKeys(skinCollection)).toEqual(['add', 'socialMessenger', 'socialWhatsapp'])
        })
        it('should return empty array on no skin collection', () => {
            expect(iconKeys()).toEqual([])
            expect(iconKeys([])).toEqual([])
        })
    })
    describe('svgIcons()', () => {
        it('should create svg icons', () => {
            const svgIconsText = `/* eslint-disable */
// @ts-nocheck
/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React, { FC } from 'react'

const EbaySvg: FC = () => (
    <svg style={{ display: 'none' }}>
        <symbol id="icon-add" viewBox="0 0 20 20"><path className="some-class-name" d="M19 9h-8V1a1 1 0 00-2 0v8H1a1 1 0 000 2h8v8a1 1 0 002 0v-8h8a1 1 0 000-2z" style={{transform: 'rotateX(10deg)', backgroundColor: 'white'}}/></symbol>
        <symbol id="icon-social-messenger" viewBox="0 0 24 24"><g clipPath="url(#clip0_41192_49714)"><path d="M12 0C5.24 0 0 4.952 0 11.64c0 3.499 1.434 6.521 3.769 8.61a.957.957 0 01.322.684l.066 2.136a.96.96 0 001.346.849l2.383-1.05a.958.958 0 01.64-.047c1.132.308 2.3.462 3.474.458 6.76 0 12-4.95 12-11.64S18.76 0 12 0zm7.206 8.956l-3.525 5.594a1.799 1.799 0 01-2.603.48l-2.803-2.103a.72.72 0 00-.868.003l-3.786 2.872c-.505.384-1.165-.221-.827-.758l3.525-5.593a1.8 1.8 0 012.603-.48l2.803 2.103a.72.72 0 00.868-.002l3.786-2.874c.505-.384 1.165.221.827.758z"/></g><defs><clipPath id="clip0_41192_49714"><path d="M0 0h24v24H0z" fill="var(--color-social-icons-foreground, #fff)"/></clipPath></defs></symbol>
        <symbol id="icon-social-whatsapp" viewBox="0 0 24 24"><path clipRule="evenodd" d="M20.5 3.5A11.9 11.9 0 0 0 16.6.9 12 12 0 0 0 12 0 12 12 0 0 0 .2 11.9a11.8 11.8 0 0 0 1.6 6L0 24l6.3-1.7a12 12 0 0 0 5.7 1.5 12 12 0 0 0 12-11.9 11.8 11.8 0 0 0-.9-4.6 11.8 11.8 0 0 0-2.6-3.8zm-8.4 18.3A10 10 0 0 1 7 20.4l-.4-.2-3.7 1 1-3.7-.3-.3a9.8 9.8 0 0 1-1.5-5.3A10 10 0 0 1 16 2.8a10 10 0 0 1 3 2.1 9.8 9.8 0 0 1 2.9 7 10 10 0 0 1-10 9.9zm5.4-7.4-2-1c-.3 0-.5-.1-.7.2l-1 1.1c-.1.2-.3.2-.6.1-.3-.2-1.3-.5-2.4-1.5a8.9 8.9 0 0 1-1.7-2c-.1-.3 0-.5.2-.6l.4-.6c.2-.1.2-.3.3-.5v-.5L9 7c-.2-.6-.4-.5-.6-.5a12 12 0 0 0-.6 0 1.1 1.1 0 0 0-.8.4c-.3.3-1 1-1 2.4 0 1.5 1 3 1.2 3.1.1.2 2.1 3.2 5.1 4.5.6.2 1.1.5 1.7.6a4 4 0 0 0 1.9.1c.6 0 1.7-.7 2-1.4l.2-1.4-.6-.3z" fillRule="evenodd"/></symbol>
    </svg>)

export default EbaySvg
`
            expect(svgIcons(skinCollection)).toEqual(svgIconsText)
        })
    })
})
