name: "reusable flow: Deploy Storybook"

on:
    workflow_call:
        inputs:
            branch:
                type: string
                required: false
                default: master
            githubActor:
                type: string
                required: true
        secrets:
            githubToken:
                required: true

jobs:
    build-storybook:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: actions/setup-node@master
              with:
                node-version: ${{ inputs.node-version }}
                cache: 'yarn'
            - name: Install dependencies
              run: yarn --frozen-lockfile
            - name: Build Storybook
              run: yarn storybook-to-ghpages --source-branch ${{ inputs.branch }} --out ${{ inputs.branch }} --ci
              env:
                GH_TOKEN: ${{ inputs.githubActor }}:${{ secrets.githubToken }}
